TARGET_JOB_TITLES = {
    "Business Operations": [
        "Business Operations Specialist",
        "Business Operations Analyst",
        "Operations Specialist",
        "Operations Analyst",
        "Business Operations Coordinator",
        "Operations Coordinator",
        "Process Analyst",
        "Process Specialist",
        "Process Coordinator",
        "Business Support Specialist",
        "Business Support Analyst",
        "Commercial Operations Specialist",
        "Sales Operations Specialist",
        "Revenue Operations Specialist",
        "RevOps Specialist",
        "Operational Excellence Specialist",
    ],
    "Business Analyst": [
        "Business Analyst",
        "Junior Business Analyst",
        "Business Process Analyst",
        "IT Business Analyst",
        "Functional Analyst",
        "Process Analyst",
        "Business Intelligence Analyst",
        "Junior Business Consultant",
        "Analytics Translator",
    ],
    "Supply Chain / Logistics / Warehouse": [
        "Supply Chain Specialist",
        "Supply Chain Analyst",
        "Supply Chain Coordinator",
        "Supply Chain Planner",
        "Demand Planner",
        "Supply Planner",
        "Logistics Coordinator",
        "Logistics Specialist",
        "Logistics Analyst",
        "Logistics Planner",
        "Transport Planner",
        "Inventory Specialist",
        "Inventory Analyst",
        "Procurement Specialist",
        "Buyer",
        "Junior Buyer",
        "Operational Buyer",
        "Purchasing Specialist",
        "Procurement Analyst",
        "Warehouse Coordinator",
        "Warehouse Specialist",
        "Import/Export Coordinator",
        "Import/Export Specialist",
    ],
    "Marketing": [
        "Marketing Specialist",
        "Marketing Coordinator",
        "Digital Marketing Specialist",
        "Digital Marketing Coordinator",
        "Marketing Analyst",
        "Marketing Intelligence Specialist",
        "Marketing Operations Specialist",
        "Growth Marketing Specialist",
        "Performance Marketing Specialist",
        "Content Marketing Specialist",
        "Product Marketing Specialist",
        "Trade Marketing Specialist",
        "CRM Marketing Specialist",
        "Marketing Communications Specialist",
        "Market Researcher",
        "Marketing Researcher",
        "Customer Insights Analyst",
    ],
    "Product Management": [
        "Product Manager",
        "Junior Product Manager",
        "Associate Product Manager",
        "Product Specialist",
        "Product Owner",
        "Junior Product Owner",
        "Product Operations Specialist",
        "Product Operations Analyst",
        "Product Analyst",
        "Product Marketing Specialist",
    ],
    "International Business / Trade": [
        "International Business Specialist",
        "International Business Coordinator",
        "International Trade Specialist",
        "International Trade Coordinator",
        "Trade Operations Specialist",
        "Trade Operations Officer",
        "Trade Support Specialist",
        "Import/Export Specialist",
        "Import/Export Coordinator",
        "Export Specialist",
        "Export Coordinator",
        "International Sales Coordinator",
        "Commercial Coordinator",
        "Trade Compliance Specialist",
        "Business Development Specialist",
        "International Business Development",
    ],
    "Research / Data": [
        "Research Analyst",
        "Research Associate",
        "Researcher",
        "Research Assistant",
        "Market Research Analyst",
        "Market Researcher",
        "Consumer Insights Analyst",
        "Customer Insights Analyst",
        "Data Analyst",
        "Junior Data Analyst",
        "Business Data Analyst",
        "Marketing Data Analyst",
        "Operations Data Analyst",
        "Supply Chain Analyst",
        "BI Analyst",
        "Business Intelligence Specialist",
        "Data/Analytics Specialist",
        "Quantitative Researcher",
    ],
    "Sales / Commercial": [
        "Sales Specialist",
        "Sales Coordinator",
        "Sales Operations Specialist",
        "Inside Sales Specialist",
        "B2B Sales Specialist",
        "Commercial Specialist",
        "Commercial Coordinator",
        "Commercial Operations Specialist",
        "Business Development Specialist",
        "Business Development Executive",
        "Account Executive",
        "Sales Analyst",
        "Commercial Analyst",
        "Sales Support Specialist",
        "Sales Administrator",
        "International Sales Specialist",
        "Export Sales Specialist",
    ],
}

BLACKLIST_TITLES = [
    "Call Center",
    "Call Centre",
    "Call Agent",
    "Contact Center Agent",
    "Contact Centre Agent",
    "Telemarketing",
    "Telemarketer",
    "Telesales",
    "Door-to-door Sales",
    "Direct Sales",
    "Street Sales",
]

ENGINEER_ALLOWED_PATTERNS = [
    "process engineer",
    "operations engineer",
    "business process engineer",
    "supply chain engineer",
    "industrial engineer",
    "continuous improvement engineer",
    "logistics engineer",
    "manufacturing engineer",
]

SENIORITY_EXCLUDE = [
    "Senior",
    "Lead",
    "Manager",
    "Director",
    "Head of",
    "VP",
    "Vice President",
    "Chief",
    "C-Level",
]

SEARCH_SOURCES = [
    "LinkedIn Jobs",
    "Indeed Netherlands",
    "Nationale Vacaturebank",
    "Intermediair",
    "Michael Page",
    "Robert Walters",
    "Hays Netherlands",
    "Yacht",
    "Randstad",
    "Adecco",
]

LOCATION = "Netherlands"
MAX_JOB_AGE_DAYS = 30
ALLOW_RELOCATION = True
SALARY_IS_FILTER = False
REMOTE_PRIORITY = "Low"

DUTCH_RULES = {
    "not_mentioned": "Normal priority",
    "preferred": "Minor disadvantage",
    "nice_to_have": "Minor disadvantage",
    "required_flexible": "Evaluate",
    "fluent_native_required": "Exclude",
    "core_customer_phone_sales_dutch": "Exclude",
}
